### ISSUE TITLE
Error: Cannot find module 'readable-stream/duplex.js

### ISSUE THREAD

**Issue by briannhinton** [mrbrianhinton/Tailwindcss-Playground-for-Playjs#2]
```{ Error: Cannot find module 'readable-stream/duplex.js'
   at Module._resolveFilename (internal/modules/cjs/loader.js:582:5)
   at resolve (internal/modules/cjs/helpers.js:30:5)
   at Anonymous function (/private/var/mobile/Containers/Data/Application/ADB31983-C54E-47CD-A764-6D7D4BF4B7FB/Documents/apps/TRAILING8697AD79-0E8F-4C1E-B901-3372625B89BB/src/node_modules/node-libs-browser/index.js:25:1)
   at Module.prototype._compile (internal/modules/cjs/loader.js:704:5)
   at Module._extensions[.js] (internal/modules/cjs/loader.js:715:3)
   at Module.prototype.load (internal/modules/cjs/loader.js:603:3)
   at tryModuleLoad (internal/modules/cjs/loader.js:537:5)
   at Module._load (internal/modules/cjs/loader.js:529:3)
   at Module.prototype.require (internal/modules/cjs/loader.js:641:3)
   at require (internal/modules/cjs/helpers.js:20:7)
   at Anonymous function (/private/var/mobile/Containers/Data/Application/ADB31983-C54E-47CD-A764-6D7D4BF4B7FB/Documents/apps/TRAILING8697AD79-0E8F-4C1E-B901-3372625B89BB/src/node_modules/webpack/lib/node/NodeSourcePlugin.js:8:1)
   at Module.prototype._compile (internal/modules/cjs/loader.js:704:5)
   at Module._extensions[.js] (internal/modules/cjs/loader.js:715:3)
   at Module.prototype.load (internal/modules/cjs/loader.js:603:3)
   at tryModuleLoad (internal/modules/cjs/loader.js:537:5)
   at Module._load (internal/modules/cjs/loader.js:529:3) code: 'MODULE_NOT_FOUND' }```

**Comment by briannhinton** [comment]
Changed build process. Closing bug.
